apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-app
    template:
      metadata:
        name: be-pod
        labals:
          app: be-app
      spec:
        containers:
        - name: be-container
          image: jramadan/devops-class-be:0.0.1