apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fe-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-app
    template:
      metadata:
        name: fe-pod
        labals:
          app: fe-app
      spec:
        containers:
        - name: fe-container
          image: jramadan/devops-class-fe:0.0.1