apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: be-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-app
  template:
    metadata:
      name: be-pod
      labels:
        app: be-app
    spec:
      containers:
      - name: be-container
        image: jramadan/devops-class-be:0.0.1